name: Playwrigth Tests
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
jobs:
  playwrighttests:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Say hello
        run: echo Hello
